export const routes = {
  back: {
    checkSession: '/api/check-session',
    login: '/auth/login',
    logout: '/auth/logout',
    fetchTables: '/db/fetch-tables',
    sessionRestore: '/auth/presence',
    fetchDatabases: '/db/fetch-databases',
    fetchRows: '/db/fetch-rows',
    runQuery: '/db/run-query',
    updateRows: '/db/update-rows',
    importDatabase: '/db/export-database',
    fetchDatabaseInfo: '/db/fetch-database-info',
    createDatabase: '/db/create-database',
    deleteDatabases: '/db/delete-databases',
    saveSettings: '/db/save-settings',
    loadSettings: '/db/load-settings',
  },
  front: {
    settings: '/settings',
    home: '/',
    account: '/account',
    login: '/login',
    // dashboard: '/dashboard',
    textView: '/text-view',
    queryView: '/query-view',
    queriesList: '/queries-list',
    tableView: '/table-view',
    newTable: '/new-table',
    dbView: '/database-view',
    userView: '/user-view',
    newUser: '/new-user',
    editUser: '/edit-user',
    usersList: '/users-list',
    newDatabase: '/new-database',
    createTable: '/create-table',
    listDatabases: '/list-databases',
    listTables: '/list-tables',
    logout: '/logout',
    networkDown: '/network-down',
  },
};
