export const routes = {
  back: {
    checkSession: '/api/check-session',
    login: '/auth/login',
    logout: '/auth/logout',
    fetchTables: '/db/fetch-tables',
    sessionRestore: '/auth/presence',
    fetchDatabases: '/db/fetch-databases',
    fetchRows: '/db/fetch-rows',
    runQuery: '/db/run-query',
    updateRows: '/db/update-rows',
    importDatabase: '/db/export-database',
    fetchDatabaseInfo: '/db/fetch-database-info',
    createDatabase: '/db/create-database',
    deleteDatabases: '/db/delete-databases',
    saveSettings: '/db/save-settings',
    loadSettings: '/db/load-settings',
  },
  front: {
    settings: '/settings',
    home: '/',
    importView: '/import-view',
    queryView: '/query-view',
    listQueries: '/list-queries',
    listUsers: '/list-users',
    listDatabases: '/list-databases',
    listTables: '/list-tables',
    listData: '/list-data',
    networkDown: '/network-down',
  },
};
